defmodule Faro.Repo.Migrations.AddGamePersistence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_turns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :index, :bigint, null: false
      add :loser_rank, :bigint, null: false
      add :loser_suit, :text, null: false
      add :winner_rank, :bigint, null: false
      add :winner_suit, :text, null: false
      add :split, :boolean, null: false, default: false
      add :bets, {:array, :map}, default: []
      add :settlements, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :round_id, :uuid, null: false
    end

    create table(:game_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:game_rounds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:game_turns) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "game_turns_round_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:game_rounds) do
      add :nonce, :bigint, null: false
      add :client_seed, :text, null: false
      add :server_seed_hash, :text, null: false
      add :server_seed, :binary
      add :algorithm_version, :text, null: false
      add :soda_rank, :bigint, null: false
      add :soda_suit, :text, null: false
      add :status, :text, null: false, default: "dealing"
      add :shuffled_deck, {:array, :map}, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_session_id,
          references(:game_sessions,
            column: :id,
            name: "game_rounds_game_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:audit_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :algorithm_version, :text, null: false
      add :server_commitment, :text, null: false
      add :server_seed, :binary, null: false
      add :client_seed, :text, null: false
      add :nonce, :bigint, null: false
      add :verified, :boolean, null: false, default: false
      add :shuffled_deck, {:array, :map}, null: false
      add :soda, :map, null: false
      add :turns, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :round_id,
          references(:game_rounds,
            column: :id,
            name: "audit_records_round_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:audit_records, [:round_id], name: "audit_records_unique_round_index")
  end

  def down do
    drop constraint(:audit_records, "audit_records_round_id_fkey")

    drop_if_exists unique_index(:audit_records, [:round_id],
                     name: "audit_records_unique_round_index"
                   )

    drop table(:audit_records)

    drop constraint(:game_rounds, "game_rounds_game_session_id_fkey")

    alter table(:game_rounds) do
      remove :game_session_id
      remove :updated_at
      remove :inserted_at
      remove :shuffled_deck
      remove :status
      remove :soda_suit
      remove :soda_rank
      remove :algorithm_version
      remove :server_seed
      remove :server_seed_hash
      remove :client_seed
      remove :nonce
    end

    drop constraint(:game_turns, "game_turns_round_id_fkey")

    alter table(:game_turns) do
      modify :round_id, :uuid
    end

    drop table(:game_rounds)

    drop table(:game_sessions)

    drop table(:game_turns)
  end
end
