defmodule Faro.Repo.Migrations.AddCascadeDeletesAndObanCleanup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:wallets, "wallets_game_session_id_fkey")

    alter table(:wallets) do
      modify :game_session_id,
             references(:game_sessions,
               column: :id,
               name: "wallets_game_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:ledger_entries, "ledger_entries_round_id_fkey")

    drop constraint(:ledger_entries, "ledger_entries_wallet_id_fkey")

    alter table(:ledger_entries) do
      modify :wallet_id,
             references(:wallets,
               column: :id,
               name: "ledger_entries_wallet_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "ledger_entries_round_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:game_turns, "game_turns_round_id_fkey")

    alter table(:game_turns) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "game_turns_round_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:game_rounds, "game_rounds_game_session_id_fkey")

    alter table(:game_rounds) do
      modify :game_session_id,
             references(:game_sessions,
               column: :id,
               name: "game_rounds_game_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:audit_records, "audit_records_round_id_fkey")

    alter table(:audit_records) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "audit_records_round_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:audit_records, "audit_records_round_id_fkey")

    alter table(:audit_records) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "audit_records_round_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:game_rounds, "game_rounds_game_session_id_fkey")

    alter table(:game_rounds) do
      modify :game_session_id,
             references(:game_sessions,
               column: :id,
               name: "game_rounds_game_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:game_turns, "game_turns_round_id_fkey")

    alter table(:game_turns) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "game_turns_round_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:ledger_entries, "ledger_entries_wallet_id_fkey")

    drop constraint(:ledger_entries, "ledger_entries_round_id_fkey")

    alter table(:ledger_entries) do
      modify :round_id,
             references(:game_rounds,
               column: :id,
               name: "ledger_entries_round_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :wallet_id,
             references(:wallets,
               column: :id,
               name: "ledger_entries_wallet_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:wallets, "wallets_game_session_id_fkey")

    alter table(:wallets) do
      modify :game_session_id,
             references(:game_sessions,
               column: :id,
               name: "wallets_game_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
