defmodule Faro.Repo.Migrations.AddWalletLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wallets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :balance_sats, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_session_id,
          references(:game_sessions,
            column: :id,
            name: "wallets_game_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:ledger_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount_sats, :bigint, null: false
      add :entry_type, :text, null: false
      add :note, :text
      add :turn_index, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :wallet_id,
          references(:wallets,
            column: :id,
            name: "ledger_entries_wallet_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :round_id,
          references(:game_rounds,
            column: :id,
            name: "ledger_entries_round_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:ledger_entries, "ledger_entries_wallet_id_fkey")

    drop constraint(:ledger_entries, "ledger_entries_round_id_fkey")

    drop table(:ledger_entries)

    drop constraint(:wallets, "wallets_game_session_id_fkey")

    drop table(:wallets)
  end
end
